# Generated by Django 5.0.6 on 2024-05-22 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actor', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_escena', models.PositiveIntegerField()),
                ('descripcion', models.TextField()),
                ('actores', models.ManyToManyField(related_name='escenas', to='actor.actor')),
            ],
        ),
        migrations.CreateModel(
            name='Dialogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actor.actor')),
                ('escena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogos', to='guion.escena')),
            ],
        ),
        migrations.CreateModel(
            name='Guion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guiones_escritos', to='usuario.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='escena',
            name='guion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escenas', to='guion.guion'),
        ),
        migrations.CreateModel(
            name='HistorialCambios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('guion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cambios', to='guion.guion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guiones', to='usuario.usuario')),
            ],
        ),
    ]
